const projects = [
    {
        id: 1,
        title: '',
        previewImage: '',
        altTitle: '',
        projectURL: '',
        gitHubRepo: '',
        projectDescription: '',
    },
    {
        id: 2,
        title: '',
        previewImage: '',
        altTitle: '',
        projectURL: '',
        gitHubRepo: '',
        projectDescription: '',
    },
    {
        id: 3,
        title: '',
        previewImage: '',
        altTitle: '',
        projectURL: '',
        gitHubRepo: '',
        projectDescription: '',
    },
    {
        id: 4,
        title: '',
        previewImage: '',
        altTitle: '',
        projectURL: '',
        gitHubRepo: '',
        projectDescription: '',
    },
    {
        id: 5,
        title: '',
        previewImage: '',
        altTitle: '',
        projectURL: '',
        gitHubRepo: '',
        projectDescription: '',
    },
    {
        id: 6,
        title: '',
        previewImage: '',
        altTitle: '',
        projectURL: '',
        gitHubRepo: '',
        projectDescription: '',
    }
]